language: php
os: linux
dist: xenial

env:
    global:
        - COMPOSER_MEMORY_LIMIT="-1"

jobs:
    include:
        -   php: 7.2
        -   php: 7.3
        -   php: 7.4
            env: RELEASE="true"

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - bin/phpunit
    - if [[ "$RELEASE" == "true" ]]; then composer run compile; fi

deploy:
    provider: releases
    token:
        secure: "qyHSXwshuTSnFgHZYjXd1/JSzDPmvFx9HYMBN3EHyUOB1YE1pBb6+mugyZYsh9OgUx6ZcCel1h+psYn9dnoYuENiYojFOV3CxAV5vXfAMDW9PyZp2zdf0feksyCSfqi8qRvzNUD21lN6v4SQ/SmbXPosIkZSq4rGt1ZnAayr+wEyB7FQ1Mnpf5ZZRoA/Pn7pUQWsZrxPPOyQOrrtMkyY4+94zYxE4rP2bW5aia7VAwIXOaXT60nciQul2a/6vHLcrMDODDki/2iGqNjYJC745E5Cko7u8WURVr+w5AT2anXS7whQMlgpJ7BpLeembJiWUx/WpU14VNNVRwIuv4BIYqU3k2YUD36iN2K0S7HSzX32hQ6OYTZcjZeKd/RwM455gvpaIR4XZKGUR8tzAPU8zbGf+MV31ZJS5wWw33jiKtZTlTHYk8HcOiHylH0Z9Vk+BWDJMZZeHzdq3FzNk9iaCUrsaeJzj1DM7iSeCY8dYxZZwQnIYuyB+uH2Su63kHpJi8DQ5JWkTYyX2zw1q/8BbR+14ZYuLH/QPjmbVYNq9b4NsCwhwiYxZmC7wHyYNGkol/taEeq78b7wgUKVp/5r/O3FHWObDCpfz5PY0llOynG10SIjL+tgg/xtuAPc3hQAu9SuQkGwtoQiIXDqZHt3ZBBSHVz9YNjT37WAzV6PWPk="
    file: dist/raml-code-generator.phar
    on:
        repo: paysera/util-raml-code-generator
        tags: true
        condition: "$RELEASE"
    skip_cleanup: true
